### ISSUE TITLE
Deprecated/Abandoned Color should be red

### ISSUE THREAD

**Issue by c33s** [jantman/repostatus.org#1]
for better visual notice, it would be better to use red as color for the abandoned badge. the suspended badge is currently best notable badge.

**Comment by jantman** [comment]
@c33s Sincerest apologies for this sitting so long. I adjusted my default watch settings for new repos because of a slew of new ones created at work, and apparently forgot to watch my own new repos... :sob:

Yeah, that's a good point, thanks. I'll have to give some thought to changing this, and how to handle API version changes.

**Comment by jantman** [comment]
This is merged and released in 1.0.0, and now live.

To pull in the changes, you'll need to update the badge URLs. The recommended way of doing this is changing them from ``badges/0.1.0/`` to ``badges/latest/``, which will always track the latest release.

**Comment by c33s** [comment]
:+1:
