### ISSUE TITLE
Make your badges the "standard" height?

### ISSUE THREAD

**Issue by jennybc** [jantman/repostatus.org#2]
The badges from repostatus are a bit shorter than those from, e.g. travisci and coveralls. This may be a little OCD but this bugs me. Any chance you could make yours match the others in height?

You can see them all next to each other here:

https://github.com/jennybc/gspreadr/blob/master/README.md

**Comment by leeper** [comment]
:+1:

**Comment by jantman** [comment]
@jennybc Sincerest apologies for this sitting so long. I adjusted my default watch settings for new repos because of a slew of new ones created at work, and apparently forgot to watch my *own* new repos... :sob: 

Now that you mentioned this, I'm terribly bothered by it as well. I'll be merging @leeper's PR in the next few days.

**Comment by jennybc** [comment]
@jantman I have somehow managed to soldier on with sightly undersized badges :smile: Thanks for looking after this and thanks @leeper for making a PR.

**Comment by leeper** [comment]
@jantman Sounds good on this and the other issues!

**Comment by jantman** [comment]
This is merged and released in 1.0.0, and now live.

To pull in the changes, you'll need to update the badge URLs. The recommended way of doing this is changing them from ``badges/0.1.0/`` to ``badges/latest/``, which will always track the latest release.

Apparently the issue here wasn't anything on my end; shields.io changed the size of their badges at some point.
