### ISSUE TITLE
Two proposed icons

### ISSUE THREAD

**Issue by leeper** [jantman/repostatus.org#3]
I think this could benefit from two additional statuses/icons:
- "Moved" to specify the code is now hosted elsewhere (thus different from abandoned)
- "Abandoned/Forked" to specify that this repo has been abandoned, but a fork continues the project

In both cases, I could imagine hyperlinks being used to point to the new locations of the code, but that would go against the current standard of pointing back to the standards document.

**Comment by jantman** [comment]
@leeper apologies - somehow I managed to not be watching my own repo, and missed this issue. A LONG time ago.

These are both good ideas, though yeah, I'm not quite sure how to handle the hyperlinking. My gut reaction is to keep the hyperlink to the standards doc and have the new location somewhere in the README itself, but that does defeat the machine-readable metadata... I'm certainly open to ideas.

**Comment by jantman** [comment]
For the record, I really like this idea, and it's deeply bothering me that I can't seem to figure out a "nice" way to implement it (i.e. keep references to both the standards doc and the new location). If anyone had any suggestions I'm certainly open to them.

**Comment by jantman** [comment]
Just revisiting this, and commenting for the record: I like the idea, but I don't feel that I can make the decision on the hyperlink target myself, as I'm not planning on using this status personally. If anyone else has input, I'd be very interested to hear it. Until then, I'm just leaving this open to see if it gets any more interest.

**Comment by RMHogervorst** [comment]
My opinion

Just leave it simple, 
add the two badges,
It is the responsibility of the repo owner who updates the readme for this badge 
to add a link.to the new location/fork

But my level of expertise is none, I like the badges as they are, used them on 2 projects.

**Comment by jantman** [comment]
@RMHogervorst thanks for chiming in. All opinions are welcome and valued...

I haven't done much with this project in a while as it fits my needs in its current state, and I realize I've let this issue sit for an embarrassingly long amount of time.

I don't think I can really give this a lot of time right now, but I'll try to get back to it. I suppose that for the markup formats that support alt text, the moved to URL could be encoded there...

**Comment by RMHogervorst** [comment]
Thanks for the reply @jantman ,
Keeping the project like this is also an option. 

If someone wants to add or remove things they can always fork your project. 
I might think about a more automated way to deploy these repostatus badges, something with time since last commit or something? Or a seperated repo for keeping track of all your projects, the image referal would stay the same. But I could change the setting in a repo and change the status of a repo from somewhere else... 

Anyway,
Thanks for the speedy reply!
Roel

**Comment by jantman** [comment]
Sorry for the delayed response.

I'd really like this to become somewhat of a standard for people who use it, so I'd prefer to incorporate any desired changes here, rather than having people run off of a fork - that works for changing badges and text, but not so much for the specification which is intended to be machine-parsable.

Automated deployment is certainly an option if you want to go that way, provided that the repo status text ends up in the repo's README. I intentionally stayed away from that, since (1) you can always pull last commit information from the repo itself, and (2) I wanted this to be a way of communicating the human maintainer's intent - i.e. I have plenty of projects that might not have had a commit in years but I still consider active and supported, and some that had commits a week or two ago but I've decided to abandon.

-Jason

**Comment by RMHogervorst** [comment]
I now use the text from your website for creation of badges. 
http://www.repostatus.org/badges/latest/active_md.txt (nice touch by the way, really useful). 

my implementation, just creating a link based on status,  is here: 
<https://github.com/RMHogervorst/badgecreatr/blob/master/R/searches.R>

I think that keeping it to one standard is indeed better. It would be bad if things break later on. 
So I would like to see the two options moved and abandoned. 

In answer to keeping the text relatively the same and adding a link, maybe a relative link?

```
[![Project Status: Moved  - The project has been moved to a new location](http://www.repostatus.org/badges/latest/moved.svg)]( moved.url "location where ")

```
and then a seperate file with the link?

It's still a bit of a workaround though.

**Comment by jantman** [comment]
So... @RMHogervorst I'm not sure how that would render across different markups.

Alternate theories:

1. Embed the new URL in the alt-text of the badge, for machine-readability. Leave the badge linked to the standards doc, but put the "moved to" or "forked to" URL in the alt-text, like:

```
[![Project Status: Moved – The project has been moved to: NEW_URL](http://www.repostatus.org/badges/latest/moved.svg)](http://www.repostatus.org/#moved)

2. Use the badge as all the others are, but require that somewhere in the same file as the badge, the following text appear (case-insensitive): "moved to: NEW_URL" or "forked to: NEW_URL". That allows the badges to function as they do now, but also adds a standard (albeit a slightly more complicated one) for machine-readability.
```

**Comment by RMHogervorst** [comment]
I hadn't thought about other markups. 

I guess your theories work just as well.

**Comment by jantman** [comment]
It's been 9 months since any further commentary. Any further thoughts on whether this is needed, or implementation?

**Comment by leeper** [comment]
Maybe the simplest thing is just add a colon so `Moved` becomes `Moved:` and `Forked` becomes `Forked:` with the implication that users would add the relevant URL (or other information) after the badge, but the badge would continue to link to the standards doc.

**Comment by jantman** [comment]
Would that really even require updating the badges, or do you think it would suffice to recommend that users add text so it appears like:

![Project Status: Moved to http://foo.com - all further development will take place there](http://img.shields.io/badge/repo%20status-Moved-red.svg) to http://foo.com

While it would complicate the parsing a bit, the specification could be updated as follows:

* Markup formats supporting alt-text for images (ReST, MD and HTML) **must** set the alt-text to a string beginning with "Project Status: Moved to <new url>"
  * Markup formats supporting alt-text **may** follow the badge with a user-visible string (as done in the example above)
* Markup formats not supporting alt-text for images (i.e. the plaintext ``.repostatus.org`` and ``repostatus.org`` files) **must** specify a new location in the format ``<badge url> to <new url>``
* If no new location/URL/authoritative fork exists, the "Abandoned" status should be used until that changes.

Thoughts, @leeper and @RMHogervorst ?

**Comment by leeper** [comment]
Works for me.

**Comment by jantman** [comment]
Ok, cool.

I did a quick [GitHub search](https://github.com/search?l=&q=http%3A%2F%2Fwww.repostatus.org%2Fbadges%2F+-user%3A%22jantman%22&ref=advsearch&type=Code&utf8=%E2%9C%93) while looking into #19 and found that, excluding my own repos, there are over 1,200 code hits for repostatus.org badge URLs. I think it's time for me to decide that decisions about adding statuses should get community feedback...

Do you think that, from a usability/user experience point of view, there's really sufficient difference between "Moved" and "Forked" for them to be separate statuses?

**Comment by jantman** [comment]
@HoverBaum @RMHogervorst @roryokane @sagikazarmark @jennybc do any of you have thoughts on either this issue or #21 ?

**Comment by HoverBaum** [comment]
Following the discussion in #19 and realizing that repostatus wants to mainly talk about two things, namely:

1. If the repo has reached a stable state yet
2. How active it is developed / how active it is supported if already stable

I have problems sorting "moved" into this. 

A repository that was moved would from my point of view be "Unsupported" if the code reached a stable state or be "Concept" if the code never reached a stable state but illustrates a direction that could be taken. That is assuming how I interpret "Concept" (see #22 ).

Now at the same time I see how the information that a project got moved to a different repository would be a very useful addition to "Unsupported" as it would inform a user that they can find support elsewhere.

However I feel that this would turn into repostatus being more of a "projectstatus" kind of thing. Walking down this road might open us up to having to include more and more statuses that in a similar way talk more about the status of a project rather than a single repository. 

If the status "Moved" should be included I feel that @jantman suggestion with a badge followed by a link would work nicely.

Will look at 21 after the weekend.

**Comment by sagikazarmark** [comment]
I agree with @HoverBaum that repo status should rather about the repo. I could imagine a separate badge for an officially accepted fork.

Another (more common) case might be migrating a repo to an organization from a personal account. In that case a repo should be discontinued, and moved to a new repo. So this need is valid, but I would separate the use case itself from repostatus. As said a discontinued badge (can't recall the exact name here) and a separate link or moved to badge would work for me.

**Comment by RMHogervorst** [comment]
Works for me too. I dont mind adding an extra badge with discontinued, or just one badge.

**Comment by jantman** [comment]
Thanks to all for the input. Since it's the weekend I'm going to let this sit for another day or two in case anyone else wants to offer input, but I'll come back to it this coming week.

**Comment by jantman** [comment]
Apologies for letting this sit so long, I've had some personal issues that prevented me from getting much work done on this.

I've added a "Moved" badge in the [issues/3 branch](https://github.com/jantman/repostatus.org/tree/issues/3).

* [svg](https://github.com/jantman/repostatus.org/blob/issues/3/badges/latest/moved.svg)
* [Specification](https://github.com/jantman/repostatus.org/commit/4c7de550b65704130a64d1821a9d15d97fc1c67f#diff-b70238c27d6583977d904d1bbe212b38) including support for the "moved to" URL
* Examples in [HTML](https://github.com/jantman/repostatus.org/blob/issues/3/badges/latest/moved_html.txt), [markdown](https://github.com/jantman/repostatus.org/blob/issues/3/badges/latest/moved_md.txt) and [rst](https://github.com/jantman/repostatus.org/blob/issues/3/badges/latest/moved_rst.txt)

Thoughts? If this is good, I'll merge it and cut a release sometime this week when I also handle the other open issues.

**Comment by jantman** [comment]
If interested, feel free to also comment on the PR, https://github.com/jantman/repostatus.org/pull/24

**Comment by jantman** [comment]
The "Moved" status was added in 2.0.0, released just now.
